# Generated by Django 3.2.16 on 2024-02-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_commented',
            new_name='post',
        ),
    ]
