# Generated by Django 3.2.16 on 2024-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_post_commented_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
